### ISSUE TITLE
[Docker] Laravel & PHP 프로젝트 도커화를 통한 복잡한 설정 경험하기

### ISSUE THREAD

**Issue by heartane** [heartane/my_code_pack#1]
## ISSUE Overview
이미지와 컨테이너, 다중 컨테이너 환경과 도커 컴포즈 그리고 유틸리티 컨테이너에 대해 전반적으로 공부했다.
이를 통해 개발 환경 셋팅에 대한 도커의 이점에 대해 깨달았고 더이상 로컬은 앱 실행을 위한 어떠한 설치에도 해방될 수 있음을 직접 확인했다. 하지만 개발 셋팅이 보다 쉬운 NodeJS에서 보다 복잡한 Laravel & PHP를 위한 환경을 도커라이징해보며 도커의 영향력을 더욱 실감해보자.
### Intended Outcome
개발 환경 구축이 보다 복잡한 Laravel & PHP를 도커화하여 쉽게 구축할 수 있는 컨테이너 환경을 만든다.
이를 통해 더 복잡한 설정에서 도커의 강력함을 맛본다.

## Task list

- [x] 컨테이너화할 타겟 설정 
  - 애플리케이션 컨테이너(PHP 인터프리터, Nginx 웹 서버, MySQL 데이터베이스)
  - 유틸리티 컨테이너(npm, composer, artisan)
- [x] 웹 서버 컨테이너
- [x] PHP 컨테이너
- [x] MySQL 컨테이너
- [x] Composer 유틸리티 컨테이너
- [x] 나머지 유틸리티 컨테이너
